name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: -*

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dump file hierarchy
      run: ls -l
    - name: Build
      run: cd ./swift-lvdb-demo \n pod install --verbose
    - name: Run tests
      run: ls -v
